#!/bin/bash

echo "===================================="
echo " Firefighter Linux"
echo "===================================="
echo "Version : V0.1 DEV"
echo "Base    : Xubuntu 24.04 LTS"
echo "Mode    : Offline-first"
echo "Purpose : Disaster response and field coordination"
echo "Website : https://firefighterlinux.org"
echo "GitHub  : https://github.com/FatihMehmetKocGitHub/FirefighterLinux"
echo "===================================="
