# packages.conf on Firefighterlinux, penguins-eggs 26.3.21
---
backend: apt
operations:
  - try_install:
      - language-pack-$LOCALE
      - libreoffice-l10n-$LOCALE
      - libreoffice-help-$LOCALE
      - firefox-$LOCALE
