# shellprocess@install_translations.conf on Firefighterlinux, penguins-eggs 26.3.21
---
message: installation of translation packages...
dontChroot: false
timeout: 1800
script:
  - /usr/libexec/calamares/calamares-l10n-helper.sh
